//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace pecopeco.progs.archive {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class takeoutTxt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal takeoutTxt() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pecopeco.progs.archive.takeoutTxt", typeof(takeoutTxt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   .js-tabs ul.tab_menu{
        ///  list-style-type:none;
        ///  margin:0px;
        ///  padding:0px;
        ///}
        ///.js-tabs ul.tab_menu li{
        ///  display:inline;
        ///  background:#666;
        ///  margin:0px;
        ///  padding:2px;
        ///}
        ///.js-tabs .tab_menu li a{
        ///  padding:3px;
        ///}
        ///.js-tabs .tab_menu li a:link,
        ///.js-tabs .tab_menu li a:visited{
        ///  background-color:#666;
        ///  color:#fff;
        ///}
        ///.js-tabs .tab_menu li a.active:link,
        ///.js-tabs .tab_menu li a.active:visited{
        ///  background-color:#444;
        ///  color:#fff;
        ///}
        ///.js-tabs .tab_menu li a:hover{
        ///  background-color:#33 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BaseCSS_css {
            get {
                return ResourceManager.GetString("BaseCSS_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encording=&quot;UTF-8&quot;?&gt;
        ///&lt;html&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=11&quot; /&gt;
        ///&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;BaseCSS.css&quot;&gt;
        ///&lt;script type=&quot;text/javascript&quot; src=&quot;BaseJS.js&quot;&gt;&lt;/script&gt;
        ///&lt;body&gt;
        ///&lt;div class=&quot;js-tabs&quot;&gt;
        ///  &lt;ul id=&quot;tab_menu1&quot; class=&quot;tab_menu&quot;&gt;
        ///    &lt;li&gt;&lt;a href=&quot;#page1-1&quot;&gt;Page 1&lt;/a&gt;&lt;/li&gt;
        ///    &lt;li&gt;&lt;a href=&quot;#page1-2&quot;&gt;Page 2&lt;/a&gt;&lt;/li&gt;
        ///    &lt;li&gt;&lt;a href=&quot;#page1-3&quot;&gt;Page 3&lt;/a&gt;&lt;/li&gt;
        ///  &lt;/ul&gt;
        ///  &lt;div  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BaseHTML {
            get {
                return ResourceManager.GetString("BaseHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   function tabMake(){
        ///    var menu = document.getElementById(&apos;tab_menu1&apos;);
        ///    var content = document.getElementById(&apos;tab_content1&apos;);
        ///    var menus = menu.getElementsByTagName(&apos;a&apos;);
        ///    var current; // 現在の状態を保持する変数
        ///    for (var i = 0, l = menus.length;i &lt; l; i++){
        ///        tab_init(menus[i], i);
        ///    }
        ///    function tab_init(link, index){
        ///        var id = link.hash.slice(1);
        ///        var page = document.getElementById(id);
        ///        if (!current){ // 状態の初期化
        ///            current = {page:page, menu:link};        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BaseJS_js {
            get {
                return ResourceManager.GetString("BaseJS_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   function start()
        ///{
        ///    //テンプレート文字列をロード
        ///    var path = window.external.ThrowTemplatePath();
        ///    var flame =document.getElementsByName(&quot;Tamplate&quot;);
        ///    flame[0].innerHTML = path;
        ///    
        ///    //保存先パス文字列をロード
        ///    var foo = window.external.ThrowSavePath();
        ///    var ooo =document.getElementsByName(&quot;PathOfSave&quot;);
        ///    ooo[0].innerHTML = foo;
        ///    
        ///    //テンプレートをロード
        ///    var info = window.external.Load(flame[0].innerHTML);
        ///    var obj = JSON.parse(info);
        ///    
        ///    //g チャプターの中の種別選択
        ///    var ChapterSelect = obj [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Diary_JavaScript_js {
            get {
                return ResourceManager.GetString("Diary_JavaScript_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encording=&quot;UTF-8&quot;?&gt;
        ///&lt;html&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=11&quot; /&gt;
        ///&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;DiaryCSS.css&quot;&gt;
        ///&lt;script type=&quot;text/javascript&quot; src=&quot;Diary_Javascript.js&quot;&gt;&lt;/script&gt;
        ///
        ///&lt;body&gt;
        ///&lt;br&gt;
        ///&lt;center&gt;
        ///	&lt;hr&gt;
        ///	&lt;h3&gt;&lt;font color=blue&gt;日記帳&lt;/font&gt;&lt;/h3&gt;
        ///	&lt;h4&gt;現在時刻 : ～～&lt;/h4&gt;
        ///	&lt;hr&gt;
        ///&lt;/center&gt;
        ///
        ///&lt;div class=Diary name=&quot;Diary&quot;&gt;
        ///	&lt;h4&gt;使用しているテンプレート&lt;/h4&gt;
        ///	Path : &lt;span name=&quot;Tamplate&quot;&gt;Default P [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DiaryBasic_html {
            get {
                return ResourceManager.GetString("DiaryBasic_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * {
        ///	position:relative;
        ///	left:0px;
        ///	top:0px;
        ///}
        ///
        ///.Diary {
        ///	position:relative;
        ///	left:200px;
        ///}
        ///.Article {
        ///	position:relative;
        ///	left:30px;
        ///}
        ///.Subject {
        ///	font-weight: bold;
        ///	color:blue;
        ///}
        ///.Substance {
        ///	font-weight: bold;
        ///}
        ///.Forms {
        ///	position:relative;
        ///	top:15px;
        ///	left:50px;
        ///}
        ///.FormNum {
        ///}
        ///.Contents {
        ///	position:relative;
        ///	left:20px;
        ///}
        ///.Save{
        ///	position:relative;
        ///	top:15px;
        ///	left:40px;
        ///} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DiaryCSS_css {
            get {
                return ResourceManager.GetString("DiaryCSS_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///    &quot;Index&quot;: {
        ///        &quot;name&quot;: &quot;Diary&quot;,
        ///        &quot;type&quot;:&quot;Template&quot;,
        ///        &quot;identifyTemplate&quot;:{
        ///            &quot;type&quot;: &quot;Hush&quot;,
        ///            &quot;code&quot;: &quot;BBBB-BBBB-BBBB-BBBB-BBBB&quot;
        ///        },
        ///        &quot;virsion&quot;: {
        ///            &quot;type&quot;: &quot;Hush&quot;,
        ///            &quot;code&quot;: &quot;AAAA-AAAA-AAAA-AAAA-AAAA&quot;,
        ///            &quot;previous&quot;:&quot;&quot;
        ///        },
        ///        &quot;DataIndex&quot;:{
        ///            &quot;name&quot;:{
        ///                &quot;regulation&quot;:[&quot;date&quot;],
        ///                &quot;Substance&quot;:&quot;Diary-yyyy-mm-dd&quot;
        ///            }
        ///        },
        ///        &quot;Contents&quot;: { [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExampleDiaryQuestion_json {
            get {
                return ResourceManager.GetString("ExampleDiaryQuestion_json", resourceCulture);
            }
        }
    }
}
