//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace pecopeco.progs.archive {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class takeoutTxt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal takeoutTxt() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pecopeco.progs.archive.takeoutTxt", typeof(takeoutTxt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encording=&quot;UTF-8&quot;?&gt;
        ///&lt;html&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=11&quot; /&gt;
        ///&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;DiaryCSS.css&quot;&gt;
        ///&lt;script type=&quot;text/javascript&quot; src=&quot;Diary_JavaScript.js&quot;&gt;&lt;/script&gt;
        ///
        ///&lt;body&gt;
        ///&lt;br&gt;
        ///&lt;center&gt;
        ///	&lt;hr&gt;
        ///	&lt;h3&gt;&lt;font color=blue&gt;譌･險伜ｸｳ&lt;/font&gt;&lt;/h3&gt;
        ///	&lt;h4&gt;迴ｾ蝨ｨ譎ょ綾 : ・橸ｽ・/h4&gt;
        ///	&lt;hr&gt;
        ///&lt;/center&gt;
        ///
        ///&lt;div class=Diary name=&quot;Diary&quot;&gt;
        ///	&lt;h4&gt;菴ｿ逕ｨ縺励※縺・ｋ繝・Φ繝励Ξ繝ｼ繝・/h4&gt;
        ///	Path : &lt;span name=&quot;Tampl [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DiaryBasic_html {
            get {
                return ResourceManager.GetString("DiaryBasic_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * {
        ///	position:relative;
        ///	left:0px;
        ///	top:0px;
        ///}
        ///
        ///.Diary {
        ///	position:relative;
        ///	left:200px;
        ///}
        ///.Article {
        ///	position:relative;
        ///	left:30px;
        ///}
        ///.Subject {
        ///	font-weight: bold;
        ///	color:blue;
        ///}
        ///.Substance {
        ///	font-weight: bold;
        ///}
        ///.Forms {
        ///	position:relative;
        ///	top:15px;
        ///	left:50px;
        ///}
        ///.FormNum {
        ///}
        ///.Contents {
        ///	position:relative;
        ///	left:20px;
        ///}
        ///.Save{
        ///	position:relative;
        ///	top:15px;
        ///	left:40px;
        ///}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DiaryCSS_css {
            get {
                return ResourceManager.GetString("DiaryCSS_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   function start()
        ///{
        ///    //繝・Φ繝励Ξ繝ｼ繝域枚蟄怜・繧偵Ο繝ｼ繝・
        ///    var path = window.external.ThrowTemplatePath();
        ///    var flame =document.getElementsByName(&quot;Tamplate&quot;);
        ///    flame[0].innerHTML = path;
        ///    
        ///    //菫晏ｭ伜・繝代せ譁・ｭ怜・繧偵Ο繝ｼ繝・
        ///    var foo = window.external.ThrowSavePath();
        ///    var ooo =document.getElementsByName(&quot;PathOfSave&quot;);
        ///    ooo[0].innerHTML = foo;
        ///    
        ///    //繝・Φ繝励Ξ繝ｼ繝医ｒ繝ｭ繝ｼ繝・
        ///    var info = window.external.Load(flame[0].innerHTML);
        ///    var obj = JSON.parse(info);
        ///    
        ///    //g 繝√Ε繝励ち繝ｼ縺ｮ荳ｭ縺ｮ遞ｮ蛻･驕ｸ謚 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DiaryJavascript_js {
            get {
                return ResourceManager.GetString("DiaryJavascript_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///    &quot;Index&quot;: {
        ///        &quot;name&quot;: &quot;Diary&quot;,
        ///        &quot;type&quot;:&quot;Template&quot;,
        ///        &quot;identifyTemplate&quot;:{
        ///            &quot;type&quot;: &quot;Hush&quot;,
        ///            &quot;code&quot;: &quot;BBBB-BBBB-BBBB-BBBB-BBBB&quot;
        ///        },
        ///        &quot;virsion&quot;: {
        ///            &quot;type&quot;: &quot;Hush&quot;,
        ///            &quot;code&quot;: &quot;AAAA-AAAA-AAAA-AAAA-AAAA&quot;,
        ///            &quot;previous&quot;:&quot;&quot;
        ///        },
        ///        &quot;DataIndex&quot;:{
        ///            &quot;name&quot;:{
        ///                &quot;regulation&quot;:[&quot;date&quot;],
        ///                &quot;Substance&quot;:&quot;Diary-yyyy-mm-dd&quot;
        ///            }
        ///        },
        ///        &quot;Contents&quot;: { [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExampleDiaryQuestion_json {
            get {
                return ResourceManager.GetString("ExampleDiaryQuestion_json", resourceCulture);
            }
        }
    }
}
